with

renamed as (
    select
        {{ var('rema_1000_store_name') }} as store_name,
        *
        {# id as product_id,
        name as product_name,
        underline,
        hf2 as brand,
        country_of_origin_code,
        pricing__price as current_price,
        pricing__max_quantity as max_quantity,
        pricing__price_over_max as price_over_max,
        pricing__is_on_discount as is_on_discount,
        pricing__normal_price as normal_price,
        pricing__price_per_kilogram as price_per_kilogram,
        pricing__price_per_unit as price_per_unit,
        pricing__is_advertised as is_advertised,
        pricing__deposit,
        description,
        description_short,
        declaration,
        declaration_old,
        'https://api.digital.rema1000.dk/api/v1' || image_url as image_url,
        'https://shop.rema1000.dk/varer/' || id as product_url,
        have_image,
        sorting,
        is_weight_item,
        median_weight,
        median_weight_unit,
        is_self_scale_item,
        assortment_code,
        extra__popularity,
        entering_date,
        department_id,
        department_name,
        category_id,
        category_name,
        modified_at,
        object_id,
        _highlight_result__id__value,
        _highlight_result__id__match_level,
        _highlight_result__name__value,
        _highlight_result__name__match_level,
        _highlight_result__hf2__value,
        _highlight_result__hf2__match_level,
        _highlight_result__category_name__value,
        _highlight_result__category_name__match_level,
        _dlt_load_id,
        _dlt_id,
        pricing__price_changes_on as price_changes_on,
        pricing__price_changes_type as price_changes_type,
        assortment_disclaimer,
        assortment_label,
        gpsr__name,
        gpsr__street,
        gpsr__postal_code,
        gpsr__city,
        gpsr__country_code,
        gpsr__website,
        item_label,
        item_disclaimer,
        temperature_zone,
        pricing__deposit__v_double,
        pricing__price_over_max__v_double,
        min_age,
        gpsr__security_alert,
        gpsr__email,
        max_sales_quantity,
        pricing__consumption_unit,
        pricing__consumption_quantity,
        gpsr__state_code #}
    from {{ source('rema', 'catalog__categories__items') }}
)

select * from renamed
